# Default initial positions for hexapod's ros2_control configuration.

initial_positions:
  coxa_joint_1: 0.0
  femur_joint_1: 0.0
  tibia_joint_1: 0.0
  coxa_joint_2: 0.0
  femur_joint_2: 0.0
  tibia_joint_2: 0.0
  coxa_joint_3: 0.0
  femur_joint_3: 0.0
  tibia_joint_3: 0.0
  coxa_joint_4: 0.0
  femur_joint_4: 0.0
  tibia_joint_4: 0.0
  coxa_joint_5: 0.0
  femur_joint_5: 0.0
  tibia_joint_5: 0.0
  coxa_joint_6: 0.0
  femur_joint_6: 0.0
  tibia_joint_6: 0.0
