initial_positions:
  # Coxa joints (hip rotation) - all at neutral position
  coxa_1_joint: 0.0
  coxa_2_joint: 0.0
  coxa_3_joint: 0.0
  coxa_4_joint: 0.0
  coxa_5_joint: 0.0
  coxa_6_joint: 0.0

  # Femur joints (thigh movement) - slightly forward lean (10 degrees)
  femur_1_joint: 0.174532925
  femur_2_joint: 0.174532925
  femur_3_joint: 0.174532925
  femur_4_joint: 0.174532925
  femur_5_joint: 0.174532925
  femur_6_joint: 0.174532925

  # Tibia joints (shin/foot movement) - bent for stance position (80 degrees)
  tibia_1_joint: 1.396263402
  tibia_2_joint: 1.396263402
  tibia_3_joint: 1.396263402
  tibia_4_joint: 1.396263402
  tibia_5_joint: 1.396263402
  tibia_6_joint: 1.396263402
