controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Position Controllers for all joints
    hexapod_position_controller:
      type: position_controllers/JointGroupPositionController

    # Individual joint controllers (if needed for testing)
    coxa_1_position_controller:
      type: position_controllers/JointPositionController
    femur_1_position_controller:
      type: position_controllers/JointPositionController
    tibia_1_position_controller:
      type: position_controllers/JointPositionController

    coxa_2_position_controller:
      type: position_controllers/JointPositionController
    femur_2_position_controller:
      type: position_controllers/JointPositionController
    tibia_2_position_controller:
      type: position_controllers/JointPositionController

    coxa_3_position_controller:
      type: position_controllers/JointPositionController
    femur_3_position_controller:
      type: position_controllers/JointPositionController
    tibia_3_position_controller:
      type: position_controllers/JointPositionController

    coxa_4_position_controller:
      type: position_controllers/JointPositionController
    femur_4_position_controller:
      type: position_controllers/JointPositionController
    tibia_4_position_controller:
      type: position_controllers/JointPositionController

    coxa_5_position_controller:
      type: position_controllers/JointPositionController
    femur_5_position_controller:
      type: position_controllers/JointPositionController
    tibia_5_position_controller:
      type: position_controllers/JointPositionController

    coxa_6_position_controller:
      type: position_controllers/JointPositionController
    femur_6_position_controller:
      type: position_controllers/JointPositionController
    tibia_6_position_controller:
      type: position_controllers/JointPositionController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - coxa_1_joint
      - femur_1_joint
      - tibia_1_joint
      - coxa_2_joint
      - femur_2_joint
      - tibia_2_joint
      - coxa_3_joint
      - femur_3_joint
      - tibia_3_joint
      - coxa_4_joint
      - femur_4_joint
      - tibia_4_joint
      - coxa_5_joint
      - femur_5_joint
      - tibia_5_joint
      - coxa_6_joint
      - femur_6_joint
      - tibia_6_joint

# Group Position Controller Configuration
hexapod_position_controller:
  ros__parameters:
    joints:
      - coxa_1_joint
      - femur_1_joint
      - tibia_1_joint
      - coxa_2_joint
      - femur_2_joint
      - tibia_2_joint
      - coxa_3_joint
      - femur_3_joint
      - tibia_3_joint
      - coxa_4_joint
      - femur_4_joint
      - tibia_4_joint
      - coxa_5_joint
      - femur_5_joint
      - tibia_5_joint
      - coxa_6_joint
      - femur_6_joint
      - tibia_6_joint
    interface_name: position

# Individual Joint Controllers
coxa_1_position_controller:
  ros__parameters:
    joint: coxa_1_joint
    interface_name: position

femur_1_position_controller:
  ros__parameters:
    joint: femur_1_joint
    interface_name: position

tibia_1_position_controller:
  ros__parameters:
    joint: tibia_1_joint
    interface_name: position

coxa_2_position_controller:
  ros__parameters:
    joint: coxa_2_joint
    interface_name: position

femur_2_position_controller:
  ros__parameters:
    joint: femur_2_joint
    interface_name: position

tibia_2_position_controller:
  ros__parameters:
    joint: tibia_2_joint
    interface_name: position

coxa_3_position_controller:
  ros__parameters:
    joint: coxa_3_joint
    interface_name: position

femur_3_position_controller:
  ros__parameters:
    joint: femur_3_joint
    interface_name: position

tibia_3_position_controller:
  ros__parameters:
    joint: tibia_3_joint
    interface_name: position

coxa_4_position_controller:
  ros__parameters:
    joint: coxa_4_joint
    interface_name: position

femur_4_position_controller:
  ros__parameters:
    joint: femur_4_joint
    interface_name: position

tibia_4_position_controller:
  ros__parameters:
    joint: tibia_4_joint
    interface_name: position

coxa_5_position_controller:
  ros__parameters:
    joint: coxa_5_joint
    interface_name: position

femur_5_position_controller:
  ros__parameters:
    joint: femur_5_joint
    interface_name: position

tibia_5_position_controller:
  ros__parameters:
    joint: tibia_5_joint
    interface_name: position

coxa_6_position_controller:
  ros__parameters:
    joint: coxa_6_joint
    interface_name: position

femur_6_position_controller:
  ros__parameters:
    joint: femur_6_joint
    interface_name: position

tibia_6_position_controller:
  ros__parameters:
    joint: tibia_6_joint
    interface_name: position
